service: recent_event.refresh_events
description: Refresh recent events from the calendar entity.
fields:
  entity_id: !select
    description: The ID of the calendar entity to refresh events from.
    options: []
  event_count: !int
    description: Number of recent events to display.
    default: 3
    min: 1
    max: 20
